## __POSTTEST 4__

#### Nama  : Deby Ayu Syakhira
#### NIM   : 2109106060
#### Kelas : Informatika B1 2021

***

# Membaca data dari file CSV _heart_2020_cleaned_

In [236]:
import pandas as pd                                              #mengimpor library pandas
import numpy as np                                               #mengimpor library numpy
from sklearn.model_selection import train_test_split             #mengimpor train_test_split dari library sklearn.model_selection
from sklearn.preprocessing import MinMaxScaler                   #mengimpor MinMaxScaler dari library sklearn.preprocessing
from sklearn.preprocessing import StandardScaler                 #mengimpor StandardScaler dari library sklearn.preprocessing
from sklearn.impute import SimpleImputer                         #mengimpor SimpleImputer dari library sklearn.impute
from sklearn.preprocessing import OneHotEncoder                  #mengimpor OneHotEncoder dari library sklearn.preprocessing
dataFrame = pd.read_csv('heart_2020_cleaned.csv')                #membaca file CSV dengan nama 'heart_2020_cleaned.csv' dan disimpan di dalam variabel dataFrame
dataFrame

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,Yes,No,No,3.0,30.0,No,Female,55-59,White,Yes,Yes,Very good,5.0,Yes,No,Yes
1,No,20.34,No,No,Yes,0.0,0.0,No,Female,80 or older,White,No,Yes,Very good,7.0,No,No,No
2,No,26.58,Yes,No,No,20.0,30.0,No,Male,65-69,White,Yes,Yes,Fair,8.0,Yes,No,No
3,No,24.21,No,No,No,0.0,0.0,No,Female,75-79,White,No,No,Good,6.0,No,No,Yes
4,No,23.71,No,No,No,28.0,0.0,Yes,Female,40-44,White,No,Yes,Very good,8.0,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,Yes,27.41,Yes,No,No,7.0,0.0,Yes,Male,60-64,Hispanic,Yes,No,Fair,6.0,Yes,No,No
319791,No,29.84,Yes,No,No,0.0,0.0,No,Male,35-39,Hispanic,No,Yes,Very good,5.0,Yes,No,No
319792,No,24.24,No,No,No,0.0,0.0,No,Female,45-49,Hispanic,No,Yes,Good,6.0,No,No,No
319793,No,32.81,No,No,No,0.0,0.0,No,Female,25-29,Hispanic,No,No,Good,12.0,No,No,No
319794,No,46.56,No,No,No,0.0,0.0,No,Female,80 or older,Hispanic,No,Yes,Good,8.0,No,No,No

***

1. __Membagi dataset menjadi training set dan testing set dengan proporsi 70:30__

In [237]:
x = dataFrame.iloc[:,1:] #mengambil semua kolom kecuali kolom pertama dan menyimpannya dalam variabel x
y = dataFrame.loc[:,'HeartDisease'] #mengambil kolom 'HeartDisease' dan menyimpannya dalam variabel y


x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3) #memisahkan data menjadi training set (70%) dan testing set (30%)
print("|=======================|")
print("|   PEMBAGIAN DATASET   |")
print("|=======================|")
print("|X_train :", x_train.shape, "|") #menampilkan dimensi x_train
print("|X_test  :", x_test.shape, " |")   #menampilkan dimensi x_test
print("|y_train :", y_train.shape, "   |") #menampilkan dimensi y_train
print("|y_test  :", y_test.shape, "    |")  #menampilkan dimensi y_test
print("|=======================|")

|=======================|
|   PEMBAGIAN DATASET   |
|=======================|
|X_train : (223856, 17) |
|X_test  : (95939, 17)  |
|y_train : (223856,)    |
|y_test  : (95939,)     |
|=======================|

***

2. __Melakukan normalisasi data pada salah satu attribute, yaitu pada atribut 'BMI' menggunakan Min Max scaler__

In [238]:
copydata = dataFrame.copy() #copy dataFrame

mms = MinMaxScaler() #membuat objek MinMaxScaler

attribute  = 'BMI' #menentukan atribut yang akan dinormalisasi (BMI)
copydata[attribute] = mms.fit_transform(copydata[[attribute]]) #proses normalisasi

copydata['BMI'] = copydata['BMI'].round(2) #membulatkan nilai dari kolom 'BMI' menjadi 2 desimal

#menampilkan data yang sudah dinormalisasi
print("================================================================================")
print("|             MENAMPILKAN DATA SETELAH MELAKUKAN NORMALISASI                   |")
print("================================================================================")
print(copydata)
#menampilkan nilai minimum dan maksimum dari kolom 'BMI' setelah dinormalisasi
print("|==============================================================================|")
print("|          MENAMPILKAN NILAI MIN & MAX SETELAH MELAKUKAN NORMALISASI           |")
print("|==============================================================================|")
print("|Nilai Minimum  : {:.1f}                                                          |".format(copydata[attribute].min()))
print("|Nilai Maksimum : {:.1f}                                                          |".format(copydata[attribute].max()))
print("|==============================================================================|")

================================================================================
|             MENAMPILKAN DATA SETELAH MELAKUKAN NORMALISASI                   |
================================================================================
       HeartDisease   BMI Smoking AlcoholDrinking Stroke  PhysicalHealth  \
0                No  0.06     Yes              No     No             3.0
1                No  0.10      No              No    Yes             0.0
2                No  0.18     Yes              No     No            20.0
3                No  0.15      No              No     No             0.0
4                No  0.14      No              No     No            28.0
...             ...   ...     ...             ...    ...             ...
319790          Yes  0.19     Yes              No     No             7.0
319791           No  0.22     Yes              No     No             0.0
319792           No  0.15      No              No     No             0.0
319793           No  0.25      No              No     No             0.0
319794           No  0.42      No              No     No             0.0

        MentalHealth DiffWalking     Sex  AgeCategory      Race Diabetic  \
0               30.0          No  Female        55-59     White      Yes
1                0.0          No  Female  80 or older     White       No
2               30.0          No    Male        65-69     White      Yes
3                0.0          No  Female        75-79     White       No
4                0.0         Yes  Female        40-44     White       No
...              ...         ...     ...          ...       ...      ...
319790           0.0         Yes    Male        60-64  Hispanic      Yes
319791           0.0          No    Male        35-39  Hispanic       No
319792           0.0          No  Female        45-49  Hispanic       No
319793           0.0          No  Female        25-29  Hispanic       No
319794           0.0          No  Female  80 or older  Hispanic       No

       PhysicalActivity  GenHealth  SleepTime Asthma KidneyDisease SkinCancer
0                   Yes  Very good        5.0    Yes            No        Yes
1                   Yes  Very good        7.0     No            No         No
2                   Yes       Fair        8.0    Yes            No         No
3                    No       Good        6.0     No            No        Yes
4                   Yes  Very good        8.0     No            No         No
...                 ...        ...        ...    ...           ...        ...
319790               No       Fair        6.0    Yes            No         No
319791              Yes  Very good        5.0    Yes            No         No
319792              Yes       Good        6.0     No            No         No
319793               No       Good       12.0     No            No         No
319794              Yes       Good        8.0     No            No         No

[319795 rows x 18 columns]
|==============================================================================|
|          MENAMPILKAN NILAI MIN & MAX SETELAH MELAKUKAN NORMALISASI           |
|==============================================================================|
|Nilai Minimum  : 0.0                                                          |
|Nilai Maksimum : 1.0                                                          |
|==============================================================================|

***

3. __Melakukan standarisasi pada dataset__

In [239]:
cdata = dataFrame.copy() #copy dataFrame

cNumerik = ['BMI', 'PhysicalHealth', 'MentalHealth', 'SleepTime'] #menentukan kolom numerik yang akan distandarisasi

ss = StandardScaler() #membuat objek StandardScaler
scdata = ss.fit_transform(cdata[cNumerik]) #proses standarisasi

#menampilkan data, standar deviasi dan nilai rata-rata sebelum melakukan standarisasi
print("================================================================================")
print("|             MENAMPILKAN DATA SEBELUM MELAKUKAN STANDARISASI                  |")
print("================================================================================")
print(cdata[cNumerik])

print("\n=============================")
print("|   STANDAR DEVIASI DATA    |")
print("=============================")
print(cdata[cNumerik].std().round(1))
print("\n=============================")
print("|      RATA-RATA DATA       |")
print("=============================")
print(cdata[cNumerik].mean().round(1))

#menampilkan data, standar deviasi dan nilai rata-rata setalah melakukan standarisasi
print("================================================================================")
print("|             MENAMPILKAN DATA SETELAH MELAKUKAN STANDARISASI                  |")
print("================================================================================")
print(pd.DataFrame(scdata, columns=cNumerik))
print("\n=============================")
print("|   STANDAR DEVIASI DATA    |")
print("=============================")
print(pd.DataFrame(scdata, columns=cNumerik).std().round(1))
print("\n=============================")
print("|      RATA-RATA DATA       |")
print("=============================")
print(pd.DataFrame(scdata, columns=cNumerik).mean().round(1))

================================================================================
|             MENAMPILKAN DATA SEBELUM MELAKUKAN STANDARISASI                  |
================================================================================
          BMI  PhysicalHealth  MentalHealth  SleepTime
0       16.60             3.0          30.0        5.0
1       20.34             0.0           0.0        7.0
2       26.58            20.0          30.0        8.0
3       24.21             0.0           0.0        6.0
4       23.71            28.0           0.0        8.0
...       ...             ...           ...        ...
319790  27.41             7.0           0.0        6.0
319791  29.84             0.0           0.0        5.0
319792  24.24             0.0           0.0        6.0
319793  32.81             0.0           0.0       12.0
319794  46.56             0.0           0.0        8.0

[319795 rows x 4 columns]

=============================
|   STANDAR DEVIASI DATA    |
=============================
BMI               6.4
PhysicalHealth    8.0
MentalHealth      8.0
SleepTime         1.4
dtype: float64

=============================
|      RATA-RATA DATA       |
=============================
BMI               28.3
PhysicalHealth     3.4
MentalHealth       3.9
SleepTime          7.1
dtype: float64
================================================================================
|             MENAMPILKAN DATA SETELAH MELAKUKAN STANDARISASI                  |
================================================================================
             BMI  PhysicalHealth  MentalHealth  SleepTime
0      -1.844750       -0.046751      3.281069  -1.460354
1      -1.256338       -0.424070     -0.490039  -0.067601
2      -0.274603        2.091388      3.281069   0.628776
3      -0.647473       -0.424070     -0.490039  -0.763977
4      -0.726138        3.097572     -0.490039   0.628776
...          ...             ...           ...        ...
319790 -0.144019        0.456341     -0.490039  -0.763977
319791  0.238291       -0.424070     -0.490039  -1.460354
319792 -0.642753       -0.424070     -0.490039  -0.763977
319793  0.705560       -0.424070     -0.490039   3.414282
319794  2.868839       -0.424070     -0.490039   0.628776

[319795 rows x 4 columns]

=============================
|   STANDAR DEVIASI DATA    |
=============================
BMI               1.0
PhysicalHealth    1.0
MentalHealth      1.0
SleepTime         1.0
dtype: float64

=============================
|      RATA-RATA DATA       |
=============================
BMI               0.0
PhysicalHealth    0.0
MentalHealth     -0.0
SleepTime         0.0
dtype: float64

***

4. __Melakukan Data cleaning pada Data dengan nilai null__

- __Mengecek apakah ada nilai null di dalam dataset__

In [240]:
dataFrame.isna().sum()

HeartDisease        0
BMI                 0
Smoking             0
AlcoholDrinking     0
Stroke              0
PhysicalHealth      0
MentalHealth        0
DiffWalking         0
Sex                 0
AgeCategory         0
Race                0
Diabetic            0
PhysicalActivity    0
GenHealth           0
SleepTime           0
Asthma              0
KidneyDisease       0
SkinCancer          0
dtype: int64

- __Karena dataset tidak memiliki nilai null, maka langkah selanjutnya yaitu membuat dataset agar memiliki nilai null__

In [241]:
kolom = ['Smoking', 'AlcoholDrinking', 'MentalHealth', 'SleepTime' ] #menentukan kolom yang akan diubah nilainya menjadi Null secara acak

probability = 0.5 #menentukan probabilitas munculnya nilai null setiap kolom, yaitu 50%

#menggunakan perulangan untuk menjelajahi setiap baris
for baris in range(len(dataFrame)):
    #memilih secara acak salah satu dari kolom yang sudah ditentukan sebelumnya
    kol = np.random.choice(kolom)
    #memeriksa apakah nilai acak kurang dari probabilitas yang telah ditentukan
    if np.random.rand() < probability:
        #jika ya, maka nilai di kolom tersebut diubah menjadi None (Null)
        dataFrame.at[baris, kol] = None

print(dataFrame) #menampilkan data yang sudah memiliki nilai null
print(dataFrame.isna().sum()) #menampilkan jumlah nilai null di setiap kolom

       HeartDisease    BMI Smoking AlcoholDrinking Stroke  PhysicalHealth  \
0                No  16.60     Yes              No     No             3.0
1                No  20.34      No              No    Yes             0.0
2                No  26.58     Yes              No     No            20.0
3                No  24.21      No              No     No             0.0
4                No  23.71      No              No     No            28.0
...             ...    ...     ...             ...    ...             ...
319790          Yes  27.41     Yes              No     No             7.0
319791           No  29.84     Yes              No     No             0.0
319792           No  24.24      No              No     No             0.0
319793           No  32.81      No              No     No             0.0
319794           No  46.56      No              No     No             0.0

        MentalHealth DiffWalking     Sex  AgeCategory      Race Diabetic  \
0               30.0          No  Female        55-59     White      Yes
1                NaN          No  Female  80 or older     White       No
2                NaN          No    Male        65-69     White      Yes
3                NaN          No  Female        75-79     White       No
4                0.0         Yes  Female        40-44     White       No
...              ...         ...     ...          ...       ...      ...
319790           0.0         Yes    Male        60-64  Hispanic      Yes
319791           0.0          No    Male        35-39  Hispanic       No
319792           NaN          No  Female        45-49  Hispanic       No
319793           0.0          No  Female        25-29  Hispanic       No
319794           NaN          No  Female  80 or older  Hispanic       No

       PhysicalActivity  GenHealth  SleepTime Asthma KidneyDisease SkinCancer
0                   Yes  Very good        5.0    Yes            No        Yes
1                   Yes  Very good        7.0     No            No         No
2                   Yes       Fair        8.0    Yes            No         No
3                    No       Good        6.0     No            No        Yes
4                   Yes  Very good        8.0     No            No         No
...                 ...        ...        ...    ...           ...        ...
319790               No       Fair        6.0    Yes            No         No
319791              Yes  Very good        5.0    Yes            No         No
319792              Yes       Good        6.0     No            No         No
319793               No       Good       12.0     No            No         No
319794              Yes       Good        8.0     No            No         No

[319795 rows x 18 columns]
HeartDisease            0
BMI                     0
Smoking             39724
AlcoholDrinking     39918
Stroke                  0
PhysicalHealth          0
MentalHealth        39933
DiffWalking             0
Sex                     0
AgeCategory             0
Race                    0
Diabetic                0
PhysicalActivity        0
GenHealth               0
SleepTime           40143
Asthma                  0
KidneyDisease           0
SkinCancer              0
dtype: int64

- __Mengganti nilai null sesuai dengan ketentuan__

In [242]:
imputers = {} #membuat dictionary kosong untuk menyimpan imputers

#menggunakan perulangan untuk menjelajahi setiap kolom
for kol in kolom:
    #jika tipe data kolom adalah 'object', akan mengisi nilai yang Null dengan 'Unknown'
    if dataFrame[kol].dtype == 'object':
        dataFrame[kol].fillna('Unknown', inplace=True)
    #jika tipe data kolom adalah 'int64', akan mengisi nilai yang Null menggunakan SimpleImputer dengan strategi 'mean'
    elif dataFrame[kol].dtype == 'int64':
        imputer = SimpleImputer(strategy = 'mean')
        dataFrame[kol] = imputer.fit_transform(dataFrame[[kol]])
    #jika tipe data kolom adalah 'float64', akan mengisi nilai yang Null menggunakan SimpleImputer dengan strategi 'median'
    elif dataFrame[kol].dtype == 'float64':
        imputer = SimpleImputer(strategy = 'median')
        dataFrame[kol] = imputer.fit_transform(dataFrame[[kol]])

#menampilkan data setelah melakukan subtitusi nilai Null
print(dataFrame)
print(dataFrame.isna().sum())

       HeartDisease    BMI Smoking AlcoholDrinking Stroke  PhysicalHealth  \
0                No  16.60     Yes              No     No             3.0
1                No  20.34      No              No    Yes             0.0
2                No  26.58     Yes              No     No            20.0
3                No  24.21      No              No     No             0.0
4                No  23.71      No              No     No            28.0
...             ...    ...     ...             ...    ...             ...
319790          Yes  27.41     Yes              No     No             7.0
319791           No  29.84     Yes              No     No             0.0
319792           No  24.24      No              No     No             0.0
319793           No  32.81      No              No     No             0.0
319794           No  46.56      No              No     No             0.0

        MentalHealth DiffWalking     Sex  AgeCategory      Race Diabetic  \
0               30.0          No  Female        55-59     White      Yes
1                0.0          No  Female  80 or older     White       No
2                0.0          No    Male        65-69     White      Yes
3                0.0          No  Female        75-79     White       No
4                0.0         Yes  Female        40-44     White       No
...              ...         ...     ...          ...       ...      ...
319790           0.0         Yes    Male        60-64  Hispanic      Yes
319791           0.0          No    Male        35-39  Hispanic       No
319792           0.0          No  Female        45-49  Hispanic       No
319793           0.0          No  Female        25-29  Hispanic       No
319794           0.0          No  Female  80 or older  Hispanic       No

       PhysicalActivity  GenHealth  SleepTime Asthma KidneyDisease SkinCancer
0                   Yes  Very good        5.0    Yes            No        Yes
1                   Yes  Very good        7.0     No            No         No
2                   Yes       Fair        8.0    Yes            No         No
3                    No       Good        6.0     No            No        Yes
4                   Yes  Very good        8.0     No            No         No
...                 ...        ...        ...    ...           ...        ...
319790               No       Fair        6.0    Yes            No         No
319791              Yes  Very good        5.0    Yes            No         No
319792              Yes       Good        6.0     No            No         No
319793               No       Good       12.0     No            No         No
319794              Yes       Good        8.0     No            No         No

[319795 rows x 18 columns]
HeartDisease        0
BMI                 0
Smoking             0
AlcoholDrinking     0
Stroke              0
PhysicalHealth      0
MentalHealth        0
DiffWalking         0
Sex                 0
AgeCategory         0
Race                0
Diabetic            0
PhysicalActivity    0
GenHealth           0
SleepTime           0
Asthma              0
KidneyDisease       0
SkinCancer          0
dtype: int64

***

5. __Melakukan Data cleaning pada data dengan nilai duplikat__

In [243]:
dataFrame.duplicated().sum() #menghitung jumlah data yang duplikat

14328

In [244]:
dataFrame.drop_duplicates(inplace =True) #menghapus data yang duplikat
dataFrame.duplicated().sum() #memeriksa jumlah data yang duplikat sudah terhapus atau belum

0

***

6. __Mengganti tipe data dari salah satu attribute angka__

In [245]:
before = dataFrame['BMI'].dtype #memeriksa tipe data awal dari kolom 'BMI'
print("|==============================================================================|")
print("|Tipe data awal dari Attribute 'BMI':", before,"                                  |")

dataFrame['BMI'] = CDATA['BMI'].astype(np.int64) #mengubah tipe data kolom 'BMI' menjadi int64

#memeriksa tipe data dari kolom 'BMI' setelah perubahan
after = dataFrame['BMI'].dtype
print("|Tipe data setelah perubahan Attribute 'BMI':", after,"                            |")
print("|==============================================================================|")
#menampilkan data setelah perubahan
print(dataFrame)

|==============================================================================|
|Tipe data awal dari Attribute 'BMI': float64                                  |
|Tipe data setelah perubahan Attribute 'BMI': int64                            |
|==============================================================================|
       HeartDisease  BMI Smoking AlcoholDrinking Stroke  PhysicalHealth  \
0                No   16     Yes              No     No             3.0
1                No   20      No              No    Yes             0.0
2                No   26     Yes              No     No            20.0
3                No   24      No              No     No             0.0
4                No   23      No              No     No            28.0
...             ...  ...     ...             ...    ...             ...
319790          Yes   27     Yes              No     No             7.0
319791           No   29     Yes              No     No             0.0
319792           No   24      No              No     No             0.0
319793           No   32      No              No     No             0.0
319794           No   46      No              No     No             0.0

        MentalHealth DiffWalking     Sex  AgeCategory      Race Diabetic  \
0               30.0          No  Female        55-59     White      Yes
1                0.0          No  Female  80 or older     White       No
2                0.0          No    Male        65-69     White      Yes
3                0.0          No  Female        75-79     White       No
4                0.0         Yes  Female        40-44     White       No
...              ...         ...     ...          ...       ...      ...
319790           0.0         Yes    Male        60-64  Hispanic      Yes
319791           0.0          No    Male        35-39  Hispanic       No
319792           0.0          No  Female        45-49  Hispanic       No
319793           0.0          No  Female        25-29  Hispanic       No
319794           0.0          No  Female  80 or older  Hispanic       No

       PhysicalActivity  GenHealth  SleepTime Asthma KidneyDisease SkinCancer
0                   Yes  Very good        5.0    Yes            No        Yes
1                   Yes  Very good        7.0     No            No         No
2                   Yes       Fair        8.0    Yes            No         No
3                    No       Good        6.0     No            No        Yes
4                   Yes  Very good        8.0     No            No         No
...                 ...        ...        ...    ...           ...        ...
319790               No       Fair        6.0    Yes            No         No
319791              Yes  Very good        5.0    Yes            No         No
319792              Yes       Good        6.0     No            No         No
319793               No       Good       12.0     No            No         No
319794              Yes       Good        8.0     No            No         No

[305467 rows x 18 columns]

***

7. __Melakukan one hot encoding pada dataset__

In [246]:
encoded = pd.get_dummies(dataFrame[['Sex']]) #menggunakan 'pd.get_dummies' untuk membuat kolom baru berdasarkan kategori dalam kolom 'Sex'
dataFrame = dataFrame.drop('Sex', axis = 1) #menghapus kolom 'Sex' dari data yang asli
df = dataFrame.join(encoded) #menggabungkan data asli dengan data hasil onehot encoding

df['Sex'] = df['Sex_Female'].fillna(df['Sex_Male']) #mengisi kolom 'Sex' 

df.drop(['Sex_Male', 'Sex_Female'], axis = 1, inplace = True) #menghapus kolom 'Sex_Male" dan 'Sex_Female'

columns = df.columns.tolist()
columns.insert(columns.index('AgeCategory'), columns.pop(columns.index('Sex'))) #memindahkan kolom 'Sex' ke posisi setelah kolom 'AgeCategory' (Biar sama seperti data yang asli)
df = df[columns] #mengganti urutan kolom sesuai dengan yang telah ditentukan sebelumnya
df #menampilkan data setalah melakukan onehot encoding

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16,Yes,No,No,3.0,30.0,No,1,55-59,White,Yes,Yes,Very good,5.0,Yes,No,Yes
1,No,20,No,No,Yes,0.0,0.0,No,1,80 or older,White,No,Yes,Very good,7.0,No,No,No
2,No,26,Yes,No,No,20.0,0.0,No,0,65-69,White,Yes,Yes,Fair,8.0,Yes,No,No
3,No,24,No,No,No,0.0,0.0,No,1,75-79,White,No,No,Good,6.0,No,No,Yes
4,No,23,No,No,No,28.0,0.0,Yes,1,40-44,White,No,Yes,Very good,8.0,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,Yes,27,Yes,No,No,7.0,0.0,Yes,0,60-64,Hispanic,Yes,No,Fair,6.0,Yes,No,No
319791,No,29,Yes,No,No,0.0,0.0,No,0,35-39,Hispanic,No,Yes,Very good,5.0,Yes,No,No
319792,No,24,No,No,No,0.0,0.0,No,1,45-49,Hispanic,No,Yes,Good,6.0,No,No,No
319793,No,32,No,No,No,0.0,0.0,No,1,25-29,Hispanic,No,No,Good,12.0,No,No,No
319794,No,46,No,No,No,0.0,0.0,No,1,80 or older,Hispanic,No,Yes,Good,8.0,No,No,No

***